// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnect(arg1) {
  return window['go']['main']['App']['AddConnect'](arg1);
}

export function AddHistory(arg1) {
  return window['go']['main']['App']['AddHistory'](arg1);
}

export function CloseConnect(arg1) {
  return window['go']['main']['App']['CloseConnect'](arg1);
}

export function DeleteConnect(arg1) {
  return window['go']['main']['App']['DeleteConnect'](arg1);
}

export function DialConnect(arg1) {
  return window['go']['main']['App']['DialConnect'](arg1);
}

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function GetConnect(arg1) {
  return window['go']['main']['App']['GetConnect'](arg1);
}

export function GetDatabaseMetadata(arg1, arg2) {
  return window['go']['main']['App']['GetDatabaseMetadata'](arg1, arg2);
}

export function GetHistories() {
  return window['go']['main']['App']['GetHistories']();
}

export function GetSetting() {
  return window['go']['main']['App']['GetSetting']();
}

export function ListConnects() {
  return window['go']['main']['App']['ListConnects']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function UpdateConnect(arg1, arg2) {
  return window['go']['main']['App']['UpdateConnect'](arg1, arg2);
}

export function UpdateSetting(arg1) {
  return window['go']['main']['App']['UpdateSetting'](arg1);
}
