// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddConnect(arg1:main.ConnectConfig):Promise<void>;

export function DeleteConnect(arg1:string):Promise<void>;

export function DialConnect(arg1:string):Promise<Array<string>>;

export function GetConnect(arg1:string):Promise<main.ConnectConfig>;

export function GetSetting():Promise<main.AppSetting>;

export function ListConnects():Promise<Array<main.ConnectConfig>>;

export function OpenFileDialog():Promise<string>;

export function UpdateConnect(arg1:string,arg2:main.ConnectConfig):Promise<void>;

export function UpdateSetting(arg1:main.AppSetting):Promise<void>;
