// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnect(arg1) {
  return window['go']['main']['App']['AddConnect'](arg1);
}

export function DeleteConnect(arg1) {
  return window['go']['main']['App']['DeleteConnect'](arg1);
}

export function GetConnect(arg1) {
  return window['go']['main']['App']['GetConnect'](arg1);
}

export function GetSetting() {
  return window['go']['main']['App']['GetSetting']();
}

export function ListConnects() {
  return window['go']['main']['App']['ListConnects']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function UpdateConnect(arg1, arg2) {
  return window['go']['main']['App']['UpdateConnect'](arg1, arg2);
}

export function UpdateSetting(arg1) {
  return window['go']['main']['App']['UpdateSetting'](arg1);
}
